# coding: utf-8

"""
    Tada AI API

    API for access Tada resources

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_query_chunk_options_input import SearchQueryChunkOptionsInput

class TestSearchQueryChunkOptionsInput(unittest.TestCase):
    """SearchQueryChunkOptionsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchQueryChunkOptionsInput:
        """Test SearchQueryChunkOptionsInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchQueryChunkOptionsInput`
        """
        model = SearchQueryChunkOptionsInput()
        if include_optional:
            return SearchQueryChunkOptionsInput(
                requested_min_word_count = 1.337,
                requested_max_word_count = 1.337
            )
        else:
            return SearchQueryChunkOptionsInput(
        )
        """

    def testSearchQueryChunkOptionsInput(self):
        """Test SearchQueryChunkOptionsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
