# coding: utf-8

"""
    Tada AI API

    API for access Tada resources

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_search_controller_search_chunks(self) -> None:
        """Test case for search_controller_search_chunks

        """
        pass

    def test_space_file_controller_download(self) -> None:
        """Test case for space_file_controller_download

        """
        pass

    def test_space_file_controller_find(self) -> None:
        """Test case for space_file_controller_find

        """
        pass

    def test_spaces_controller_create(self) -> None:
        """Test case for spaces_controller_create

        """
        pass

    def test_spaces_controller_find(self) -> None:
        """Test case for spaces_controller_find

        """
        pass

    def test_spaces_controller_find_many(self) -> None:
        """Test case for spaces_controller_find_many

        """
        pass

    def test_spaces_controller_space_files(self) -> None:
        """Test case for spaces_controller_space_files

        """
        pass

    def test_spaces_controller_upload(self) -> None:
        """Test case for spaces_controller_upload

        """
        pass


if __name__ == '__main__':
    unittest.main()
