# coding: utf-8

"""
    Tada AI API

    API for access Tada resources

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_query_input import SearchQueryInput

class TestSearchQueryInput(unittest.TestCase):
    """SearchQueryInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchQueryInput:
        """Test SearchQueryInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchQueryInput`
        """
        model = SearchQueryInput()
        if include_optional:
            return SearchQueryInput(
                prompt = 'Who is in charge of ops',
                space_id = 'fdf8nvmegsmkfv98if79tk8b',
                chunk_options = openapi_client.models.search_query_chunk_options_input.SearchQueryChunkOptionsInput(
                    requested_min_word_count = 1.337, 
                    requested_max_word_count = 1.337, ),
                reranker = openapi_client.models.search_query_reranker_options_input.SearchQueryRerankerOptionsInput(
                    use_reranker = True, 
                    top_n = 1.337, 
                    threshold = 1.337, )
            )
        else:
            return SearchQueryInput(
                prompt = 'Who is in charge of ops',
        )
        """

    def testSearchQueryInput(self):
        """Test SearchQueryInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
