# coding: utf-8

"""
    Tada AI API

    API for access Tada resources

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tada_ai.models.space_files_list_dto import SpaceFilesListDto

class TestSpaceFilesListDto(unittest.TestCase):
    """SpaceFilesListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpaceFilesListDto:
        """Test SpaceFilesListDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpaceFilesListDto`
        """
        model = SpaceFilesListDto()
        if include_optional:
            return SpaceFilesListDto(
                data = [
                    tada_ai.models.space_file.SpaceFile(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = 'pvlanjb5moh57xpzq6ym76cz', 
                        original_mime_type = 'application/pdf', 
                        space_id = 'qabqfp66eeiznrf078h4c94t', 
                        path = '/foo/bar.pdf', 
                        status = 'Pending', )
                    ]
            )
        else:
            return SpaceFilesListDto(
                data = [
                    tada_ai.models.space_file.SpaceFile(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = 'pvlanjb5moh57xpzq6ym76cz', 
                        original_mime_type = 'application/pdf', 
                        space_id = 'qabqfp66eeiznrf078h4c94t', 
                        path = '/foo/bar.pdf', 
                        status = 'Pending', )
                    ],
        )
        """

    def testSpaceFilesListDto(self):
        """Test SpaceFilesListDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
